name: Build and upload binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target:
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal

      - name: Build binary for ${{ matrix.target }}
        run: |
          echo "Building for target ${{ matrix.target }} on OS ${{ matrix.os }}"
          cargo build --release --target ${{ matrix.target }}

      - name: Upload binary for ${{ matrix.target }}
        uses: actions/upload-artifact@v3
        with:
          name: ConfigConverter-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/config_converter
          retention-days: 5
